language: shell
services:
- docker

stages:
  - name: install
    # require the branch name to be master (note for PRs this is the base branch name)
    if: branch = master
  - name: script
    # require the branch name to be master (note for PRs this is the base branch name)
    if: tag = true

env:
#  matrix:
  global:
#  - DOCKER_TAG=$TRAVIS_BUILD_ID
  - DOCKER_TAG=${TRAVIS_COMMIT:0:7}
  - DEV_REPO=blademainer/hexo:$DOCKER_TAG
  - RELEASE_REPO=blademainer/hexo:$TRAVIS_TAG
  - secure: d/TMJCk2PhhIpEK4WMzKg35hHndgmm/sK687JwgChOSK+gDCLJMloJS4ofT4Zu2oefiQqPWZG42zFGSktRxPboESJef/WElrjDW+usiCcK6MI8B9PaJiRAhBlkkKPKYcw4tR6s6NoexqgX3dUMXp7oqj5qOiwytZmCehL9TIYfnkj7DeAHAPoLGaBoZ0+hvpl57p4dFZoIVe2ieo94ZYcGiY8krYWgeMMjEu3kvbPOtw2iD5oVF4EwK9QQ12wawgSj7GMhJoiC23sm8KWtNaWdLKoPzvyAPprEK/HK8VjBeJiXAoJl13/g4b6BL4XKSLiPhAIUGgf8+nqBFY22YN97nAU+v96C8EbXF+YHj/AppygzbHI8lBtcmtc8ka3IHfNOeRxxnNTOiNdx0xDsHUW/evXqwne2wgQ87jUpIDF6fdt5ZCaS8I+CatmXMjXw7vAG4+922Z8i8rBkqgYeTgjhz55QhPl41zSWzO76/2xTOmzxMe6TaFNr0vSOkvV+8Wzoelsl03C7vTUcBDfsR24oSSZd7AYwOgqw2v0TVLAn9qU0L8Xkfp2JjcbkM9XMBSfXJHOvPR+HsbBbYIb0r7XjR2qdwAdX9zZecPY8GRxoRZGz+4Xr2cSrssZWz55rJvjCJ87LvqtgZN6Y8s7MgxLjwEBgudId/d7fgR9ahP11Q=
  - secure: xG2BrjToywZS5R3NgxJgFd1Fv5HEvjtse+cQToN65f65Je/p61G5T7aSWnFy1DbQW1IluDoR1HED1lNtGoLZB4Ms3R+5Soga4Rt282MRkqLM30Rn0KmLcdmjCclbIWU3laya3GvBe6wkAJfBjX5s9CiFE9AkV3Z39d5UUrxWAeMjqFicZF2tshzDzl8hDMoJVuxSjkHtt+3RJ08Q0ghkHXq2DngjigkbNVjbACJwEIf0bJB1R5jhIqXFia68mdhXMF5dAI9PyIY2qnyesP94rQbM0WEWiMETVWSetXQR8u6scgVuYRhqCe1CbzkJv1WhQVJUI7tdIFH5szdbiYrPrJ3zmELc4UPKCxHoer8WakgQOOcPrIdl3TOvgC3msup+7uQJXzcqcar0IyWVR5Si43T/bIG8MTF9RtQl0wlRIxzpr4+zzaKIARdRcHYsfSO/kErY5XMIxdKdFsPFQNsB81MFwQ2LTzmNo3NRYdUtj3lGy03mAzjloXUwspkBN5Edrdyxks22+8LknU2EiT8gTuV7vJMGTbjSZqDMJcSwP4lcbDts9sTx5J6LnaFE3qoDmsZF3FKw3mord5JBJDIg2dHVZpNyot8AeMPZmxVopN9og8g9FjybCRd3YysKUMaeMhigphsqiPexTrzKHlFufgxgRQ+SZ8o8DXigt1QETCA=
before_install:
- env
- docker login -u$DOCKER_USER -p$DOCKER_PASS

install:
- docker build . -t $DEV_REPO && docker push $DEV_REPO
script:
- if [ -z "$TRAVIS_TAG" ]; then exit 0; fi
- docker pull $DEV_REPO
- docker tag $DEV_REPO $RELEASE_REPO && docker push $RELEASE_REPO
